config/routes.rb
Rails.application.routes.draw do

  
  root to: 'tasks#index'
  
  resources :tasks
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'
  #resources :users, only: [:index, :show, :create]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  
  belongs_to :user
  
  validates :status, presence: true, length: { maximum: 10 }

end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :tasks
  before_save { self.email.downcase! }
  has_secure_password
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
    uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  
  private
  
  def rquire_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインしました'
      redirect_to root_path
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

before_action :set_task, only: [:show, :edit, :update, :destroy]
before_action :rquire_user_logged_in
before_action :correct_user, only: [:show, :edit, :update, :destroy]

  def index
    if logged_in?
      @tasks = current_user.tasks.order(id: :desc)
    end
  end
  
  def show
  
  end
  
  def new
    @task = Task.new
  end
  
  def create
    @task = current_user.tasks.build(task_params)
    
    if @task.save
      flash[:success] = "タスクが正常に追加されました"
      redirect_to @task
    else
      flash.now[:danger] = 'タスクを追加できませんでした'
      render :new
    end
    
  end
  
  def edit

  end
   
  def update
    
    if @task.update(task_params)
      flash[:success] = "タスクが正常に更新されました"
      redirect_to @task
    else
      flash.now[:danger] = 'タスクを更新できませんでした'
      render :edit
    end
    
      
  end
  
  def destroy

    @task.destroy
    flash[:success] = 'タスクを削除しました'
    redirect_to tasks_url
      
  end
    
  private
  
  def set_task
    @task = Task.find(params[:id])
  end

  #Strong Parameter
  
  def task_params
    params.require(:task).permit(:content, :status)
  end
  
  def correct_user
    @tasks = current_user.tasks.find_by(id: params[:id])
    
    unless @tasks
      redirect_to root_url
    end
  end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  
  def index
    @users = User.order(id: :desc)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザーを登録しました'
      #session[:user_id] = @user.id
      redirect_to login_url
    else
      flash.now[:danger] = 'ユーザーを登録できませんでした'
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
    <div id="error_explanation" class="alert alert-warning">
        <ul class="mb-0">
            <% model.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/_flash_message.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Tasklits</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/flash_message' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |f| %>

    <% if task.errors.any? %>
        <div id="error_explanation">
            <ul>
                <% task.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <%= f.label :content, 'タスク' %>
    <%= f.text_field :content %>

    <%= f.label :status, 'ステータス' %>
    <%= f.text_field :status %>
    <%= f.submit '送信' %>
<% end %>

app/views/tasks/edit.html.erb
<h1>タスク編集ページ</h1>

<%= render 'form' ,task: @task %>


<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/index.html.erb
<div class="m-4">
    <div class="mb-4">
        <% if logged_in? %>
            <p>ユーザー名：<%= current_user.name %>さん</p>
            <%= link_to 'ログアウト', logout_path, method: :delete %>
        <% else %>
            <%= link_to 'ログイン', login_path %>
        <% end %>
    </div>
    
    <h1>タスク一覧</h1>
    <div class="m-4">
        <ul>
        <% @tasks.each do |task|  %>
            <li><%= link_to task.id ,task_path(task.id) %>:<%= task.content %>&gt;<%= task.status %></li>
        <% end %>
        </ul>
    </div>
    <div>
        <%= link_to '新規タスクの登録', new_task_path, class: "btn btn-primary" %>
    </div>
</div>

app/views/tasks/new.html.erb
<h1>タスク新規作成ページ</h1>

<%= render 'form' ,task: @task %>


<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/show.html.erb
<h1><%= @task.id %>の詳細</h1>

<p><%= @task.content %></p>
<p><%= @task.status %></p>

<%= link_to 'タスク一覧へ戻る', tasks_path %> | 
<%= link_to 'このタスクを編集する', edit_task_path(@task) %> | 
<%= link_to 'このタスクを削除する', @task, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>

app/views/users/index.html.erb
<div class="text-center m-3">
    <h3>ユーザーリスト</h3>
    <% if @users.any? %>
        <ul class="list-unstyled">
            <% @users.each do |user| %>
                <li><%= user.name %>
                <%= link_to ':詳細', user_path(user.id) %></li>
            <% end %>
        </ul>
    <% else %>
        <p>No users</p>
    <% end %>
    <%= link_to '新規ユーザー登録', signup_path ,class:'btn btn-primary' %>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h3>新規ユーザー登録</h3>
</div>

<div class="row">
  <div class="col-6 offset-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '登録', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="text-center m-3">
    <h3>ユーザーの詳細</h3>
    <p>ユーザー名：<%= @user.name %></p>
    <p>メールアドレス：<%= @user.email %></p>

    <%= link_to 'ユーザーリストに戻る', users_path ,class:'btn btn-primary' %>
</div>